### ISSUE TITLE
Conversion not starting when googleStorageBucket is set

### ISSUE THREAD

**Issue by dominikponniah** [google-wallet/pass-converter#17]
Everything works quite fine, but when I do want to convert a *.pkpass-File (it is a Season-Ticket including a Photo and a Logo) the error message is always the same:

```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
```

If the ```googleStorageBucket```-Value is not set, the Pass gets generated and could be added to Google Wallet.

Any ideas on how I could make it work? ```googleServiceAccountJsonPath``` and ```googleIssuerId``` is set correctly.

**Comment by stephenmcd** [comment]
Not entirely certain but it might help if you create a seperate script that saves a file to Google Cloud using the credentials/bucket you've configured - I imagine you'll get the same errors and if you can get that working, you'll solve the larger issue.

**Comment by mousey** [comment]
It's to do with the request to STORAGE.

I added a config item for the Google Project ID to the config.json

`// Google Cloud project id
  "googleProjectId": "",`

And then amended app.js to account for the new way of authenticating

`// Create a Cloud Storage client
    const storage = new Storage({projectId: config.googleProjectId, keyFilename: config.googleServiceAccountJsonPath });`
    
   And that fixed the issue for me

**Comment by stephenmcd** [comment]
I suspect this arises when separate cloud projects are used. I'll close for now.
