### ISSUE TITLE
[Request] Possibility to directly export to pdf format

### ISSUE THREAD

**Issue by kirk86** [google-wallet/pass-converter#21]
Hi, thanks for the great conversion tools.
I'd like to request if possible to have the ability to directly export .pkpasss files or google pay files to pdf format which is also very versatile and easily acceptable/readable by all devices?

Thanks!

**Comment by stephenmcd** [comment]
Hi there, I don't think this belongs in the project itself since PDF isn't a major pass file format - not to say it wouldn't be useful, but it's probably better implemented separately.
