### ISSUE TITLE
slightly unrelated question

### ISSUE THREAD

**Issue by DeadSix27** [google-wallet/pass-converter#22]
Can one import google wallet json objects direclty into wallet?
As far as I can tell you need a business profile on the google api to do all this.. 
which is probably why i get this error:
`Error creating class: GaxiosError: Permission denied. url: 'https://walletobjects.googleapis.com/walletobjects/v1/eventTicketClass/'`

tl;dr Is there a way to just have custom tickets/etc just for myself, in my wallet app without the complicated setup process?

**Comment by stephenmcd** [comment]
Hi there, a business profile account is required. If you have any other questions unrelated to the pass converter, please reach out to the support channel on the developer site.
