### ISSUE TITLE
getting safari cannot download this file (applepass-95370f2a-cd77-4bcc-b52b-be22dff45415.pkpass)

### ISSUE THREAD

**Issue by fahisayub** [google-wallet/pass-converter#24]
I am using Pass converter to convert Google Pass to Apple Pass, the output is stored in the AWS S3. when  a  user visit the link it will download the .pkpass (naming is like this: applepass-95370f2a-cd77-4bcc-b52b-be22dff45415.pkpass). but I am getting "Safari cannot download this file"  when I am using iPhone 14.

in windows by changing the user agent, it is getting downloaded

any idea how to fix this, screenshot attached below
this is the code that sent pkpass to s3 and get back the link

`if (req.passText.charAt(0) === '{') {

            try {
                const pkPassBuffer = await googleToPkPass(JSON.parse(req.passText), req.fullUrl);
                // Respond with the PKPass file
                const params = { content: pkPassBuffer, contentType: 'application/vnd.apple.pkpass', }
                const applePassUrl = await uploadToS3(params);
                res.send({ msg: 'success', url: applePassUrl })
            } catch (e) {
                console.log(e);
            }

        }`

upload to S3 :  
` // function that upload pkpass to s3

     const uploadToS3 = async ({ content, contentType }) => {
     let random = seedrandom(`${new Date().getTime()}`)();
     const keyId = uuidv4(`link/${random}`, uuidv4.URL);
     const params = {
      Bucket: bucket,
       Key: `applepass-${keyId}.pkpass`,
       Body: content,
      ContentEncoding: "base64",
       ContentType: contentType,
       };

      const uploadedfile = await s3.upload(params).promise();
       return uploadedfile.Location.replace("s3.amazonaws.com/", "");
      }; `

![Screenshot (1169)](https://github.com/google-wallet/pass-converter/assets/32778039/7b5e4a2b-ad93-4550-8d06-f3d65a5e880a)

I used pass validator to validate the pass, it says :
![image](https://github.com/google-wallet/pass-converter/assets/32778039/c100dc05-adae-49a5-81f2-906deecf492a)

**Comment by stephenmcd** [comment]
Sounds like an issue between S3 and your device.

You could potentially verify this by downloading the pass file and opening it on a Mac or emailing it to your iPhone.

**Comment by fahisayub** [comment]
I tried emailing after fixing the issue with webserviceURL and icons, but still, i get the same error that Safari cannot download this file.

**Comment by stephenmcd** [comment]
Try the troubleshooting steps here: https://github.com/google-wallet/pass-converter#apple-pkpass-2

**Comment by fahisayub** [comment]
when I tried opening the pass through the mail app it's working, previously opened it through the browser itself, is it the issue with the browser

**Comment by stephenmcd** [comment]
If you're unable to follow the debugging steps there's not much else I can suggest, please post back here if you find the solution.

**Comment by fahisayub** [comment]
yes, I got the issue it was because of the headers since I am using aws for storing the pkpass file when I return it for download I am sending it as  json content type instead of contentType: 'application/vnd.apple.pkpass', 

 The reason for showing error "Safari cannot download this file is mainly due to :

- if the contentType of the response is not  'application/vnd.apple.pkpass'
- if any of the required fields are not present in pkpass file
- if the certificate is not valid

Thank you for guiding me

**Comment by stephenmcd** [comment]
Thanks so much for posting the solution, it will definitely help others who face it.
